title: Fast Robots
email: wy82@cornell.edu
description: >- 
        Projects for ECE 4160
github_username: wy82
github: [metadata]
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
domain: wy82.github.io
url: https://wy82.github.io
baseurl: /ECE-4160
markdown: GFM
search: true
minimal_mistakes_skin: dark
include:
  - _pages
  
author:
  name   : "William Yuan"
  bio    : "A student majoring in ECE at Cornell University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wy82"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

