title: Fast Robots
email: wy82@cornell.edu
description: >- 
        A documentation of projects in ECE 4160: Fast Robots (Spring 2023).
domain: "wy82.github.io" 
baseurl: "Fast-Robots"
url: "https://wy82.github.io" 
github_username:  wy82
