title: Fast Robots
email: wy82@cornell.edu
description: >- 
        A documentation of projects in ECE 4160: Fast Robots (Spring 2023).
baseurl: "/Fast-Robots"
url: "https://wy82.github.io" 
github_username:  wy82
github: [metadata}
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: kramdown
search: true
minimal_mistakes_skin: dark
include:
  - _pages
plugins:
  - jekyll-include-cache
author:
  name   : "William Yuan"
  bio    : "A student majoring in ECE at Cornell University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wy82"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
