source "https://rubygems.org"
gem "github-pages","~> 227", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem "faraday-retry","~> 2.0"
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "webrick", "~> 1.8"
gem "minimal-mistakes-jekyll"
